// Generated by tools/design.py. Edit design/sheets instead.
package dev.ckcraft;
import java.util.Map;
import static java.util.Map.entry;
public final class GeneratedDesign {
    private GeneratedDesign() {}
    public record Scenario(String id, String label, String ck3_event, String enemy, int distance, int radius, int floor_y, int timeout_seconds, String won, String lost, String aborted, String trigger, int light_spacing) {}
    public static final Map<String, Scenario> SCENARIOS = Map.ofEntries(
        entry("travel_duel", new Scenario("travel_duel", "Reise und Wegduell", "ckcraft.1000", "courtier", 24, 20, 96, 300, "won", "lost", "aborted", "on_travel_plan_start", 5)),
        entry("free_travel", new Scenario("free_travel", "Freies Reisen", "ckcraft.1001", "none", 24, 20, 96, 600, "travelled", "aborted", "aborted", "ckcraft_free_travel_decision", 5))
    );
    public record Enemy(String id, String entity, int health_base, int health_per_prowess, int health_cap, int attack_base, int attack_per_ten_prowess, int attack_cap, String weapon, String weapon_modifiers) {}
    public static final Map<String, Enemy> ENEMIES = Map.ofEntries(
        entry("courtier", new Enemy("courtier", "minecraft:zombie", 12, 1, 60, 2, 1, 8, "minecraft:iron_sword", "none")),
        entry("none", new Enemy("none", "none", 0, 0, 0, 0, 0, 0, "none", "none"))
    );
    public record Outcome(String id, String ck3_event, String label, int prestige, int gold) {}
    public static final Map<String, Outcome> OUTCOMES = Map.ofEntries(
        entry("won", new Outcome("won", "ckcraft.2001", "Das Wegduell gewonnen", 25, 0)),
        entry("lost", new Outcome("lost", "ckcraft.2002", "Das Wegduell verloren", -10, 0)),
        entry("aborted", new Outcome("aborted", "ckcraft.2003", "Unver\u00e4ndert nach CK3 zur\u00fcckkehren", 0, 0)),
        entry("travelled", new Outcome("travelled", "ckcraft.2004", "Die Reise beendet", 0, 0))
    );
    public record Hook(String id, String kind, String target, String scenario, String guard) {}
    public static final Map<String, Hook> HOOKS = Map.ofEntries(
        entry("travel_start", new Hook("travel_start", "on_action", "on_travel_plan_start", "travel_duel", "human_enabled_not_pending")),
        entry("free_travel", new Hook("free_travel", "decision", "ckcraft_free_travel_decision", "free_travel", "human_enabled_not_pending"))
    );
    public record SystemSpec(String id, String owner, String contract, String implementation) {}
    public static final Map<String, SystemSpec> SYSTEMS = Map.ofEntries(
        entry("ck3_export", new SystemSpec("ck3_export", "ck3", "singleplayer CKCRAFT1 request/ack via GetPlayer; actual character/sequence/prowess and persistent ckcraft_opponent reference, independent of debug_log ROOT/SCOPE context", "tools/design.py")),
        entry("bridge", new SystemSpec("bridge", "python", "loopback authenticated singleplayer request/claim/result/ack state machine", "bridge/ckcraft/state.py")),
        entry("http", new SystemSpec("http", "python", "bounded JSON, no browser origins, constant time token check", "bridge/ckcraft/server.py")),
        entry("log_reader", new SystemSpec("log_reader", "python", "incremental frames, partial writes, rotation, no historic requests on initial start", "bridge/ckcraft/log_reader.py")),
        entry("ck3_return", new SystemSpec("ck3_return", "python", "guarded numeric effect command, requires actual matching CK3 acknowledgement", "bridge/ckcraft/return_command.py")),
        entry("minecraft_scene", new SystemSpec("minecraft_scene", "fabric", "isolated dimension, real combat result, inventory recovery, abort and timeout", "minecraft/src/main/java/dev/ckcraft/CKCraft.java")),
        entry("network_client", new SystemSpec("network_client", "fabric", "asynchronous HTTP with main-thread game changes", "minecraft/src/main/java/dev/ckcraft/BridgeClient.java")),
        entry("owned_entity_cleanup", new SystemSpec("owned_entity_cleanup", "fabric", "only remove tagged CKCraft duelist leftovers on entity load; preserve other entities", "minecraft/src/main/java/dev/ckcraft/CKCraft.java")),
        entry("player_recovery", new SystemSpec("player_recovery", "fabric", "save original state before scene; persist restored player data before marking restored or clearing recovery", "minecraft/src/main/java/dev/ckcraft/RecoveryStore.java"))
    );
}
