#!/usr/bin/env python3
"""Validate the design tables and generate each row's record and CK3 scripts."""
from pathlib import Path
import argparse
import json
import re
import sys

ROOT = Path(__file__).resolve().parents[1]
SHEETS = ROOT / "design" / "sheets"
TYPES = {"string":"String", "int":"int"}
CLASSES = {"scenarios":"Scenario", "enemies":"Enemy", "outcomes":"Outcome", "hooks":"Hook", "systems":"SystemSpec"}


def load(directory=SHEETS):
    return {p.stem:json.loads(p.read_text(encoding="utf-8")) for p in sorted(directory.glob("*.json"))}


def preflight(tables, root=ROOT):
    errors = []
    if set(tables) != set(CLASSES):
        errors.append("Expected scenarios, enemies, outcomes, hooks and systems tables")
    ids = {}
    for name,table in tables.items():
        columns, rows = table.get("columns",{}), table.get("rows",[])
        if not columns or "id" not in columns or not rows:
            errors.append(f"{name}: columns/id/rows missing")
        ids[name] = set()
        for i,row in enumerate(rows):
            label = f"{name}[{i}]"
            for column,kind in columns.items():
                if column not in row or row[column] is None or row[column] == "":
                    errors.append(f"{label}.{column}: unfilled cell")
                elif kind == "int" and type(row[column]) is not int:
                    errors.append(f"{label}.{column}: expected integer")
                elif (kind == "string" or kind.startswith("ref:")) and not isinstance(row[column],str):
                    errors.append(f"{label}.{column}: expected string")
                elif kind not in TYPES and not kind.startswith("ref:"):
                    errors.append(f"{label}.{column}: unknown column type")
            for column in set(row)-set(columns):
                errors.append(f"{label}.{column}: undeclared column")
            rid = row.get("id")
            if not isinstance(rid,str) or not re.fullmatch(r"[a-z][a-z0-9_]*",rid):
                errors.append(f"{label}.id: invalid identifier")
            elif rid in ids[name]:
                errors.append(f"{label}.id: duplicate {rid}")
            else:
                ids[name].add(rid)
    for name,table in tables.items():
        for row in table.get("rows",[]):
            for column,kind in table.get("columns",{}).items():
                if kind.startswith("ref:") and row.get(column) not in ids.get(kind[4:],set()):
                    errors.append(f"{name}.{row.get('id')}.{column}: unresolved reference {row.get(column)}")
    if errors:
        return errors
    events = []
    for name in ["scenarios","outcomes"]:
        for row in tables[name]["rows"]:
            events.append(row["ck3_event"])
            if not re.fullmatch(r"ckcraft\.\d{4}",row["ck3_event"]):
                errors.append(f"{name}.{row['id']}: unsafe event ID")
    if len(events) != len(set(events)):
        errors.append("CK3 event IDs must be unique")
    for row in tables["scenarios"]["rows"]:
        if not (8 <= row["radius"] <= 32 and 1 <= row["distance"] < 2*row["radius"] and 32 <= row["floor_y"] <= 250 and 30 <= row["timeout_seconds"] <= 1800 and 1 <= row['light_spacing'] <= 8):
            errors.append(f"scenarios.{row['id']}: invalid scene bounds")
    for row in tables["enemies"]["rows"]:
        if row['weapon_modifiers'] != 'none' or not re.fullmatch(r'minecraft:[a-z_]+|none',row['weapon']):
            errors.append(f"enemies.{row['id']}: unsupported weapon attributes")
        if any(v < 0 for k,v in row.items() if type(v) is int) or row["health_cap"] < row["health_base"] or row["attack_cap"] < row["attack_base"]:
            errors.append(f"enemies.{row['id']}: invalid combat bounds")
    for row in tables["outcomes"]["rows"]:
        if abs(row["prestige"]) > 100 or abs(row["gold"]) > 100:
            errors.append(f"outcomes.{row['id']}: excessive reward")
    for row in tables["hooks"]["rows"]:
        if row["guard"] != "human_enabled_not_pending" or row["kind"] not in {"decision","on_action"} or not re.fullmatch(r"[a-z][a-z0-9_]*",row["target"]):
            errors.append(f"hooks.{row['id']}: unsupported hook or guard")
    for row in tables["systems"]["rows"]:
        path = root / row["implementation"]
        if not path.resolve().is_relative_to(root.resolve()) or not path.is_file():
            errors.append(f"systems.{row['id']}: implementation missing")
    return errors


def java(tables):
    lines = ["// Generated by tools/design.py. Edit design/sheets instead.","package dev.ckcraft;","import java.util.Map;","import static java.util.Map.entry;","public final class GeneratedDesign {","    private GeneratedDesign() {}"]
    for table,cls in CLASSES.items():
        columns = tables[table]["columns"]
        fields = ", ".join(f"{TYPES.get(kind,'String')} {column}" for column,kind in columns.items())
        lines.append(f"    public record {cls}({fields}) {{}}")
        lines.append(f"    public static final Map<String, {cls}> {table.upper()} = Map.ofEntries(")
        entries = []
        for row in tables[table]["rows"]:
            values = ", ".join(json.dumps(row[c],ensure_ascii=True) for c in columns)
            entries.append(f"        entry({json.dumps(row['id'])}, new {cls}({values}))")
        lines.append(",\n".join(entries)+"\n    );")
    return "\n".join(lines)+"\n}\n"


GUARD = "is_ai = no has_character_flag = ckcraft_enabled NOT = { has_character_flag = ckcraft_pending }"


def generate(tables):
    result = {"minecraft/src/main/java/dev/ckcraft/GeneratedDesign.java":java(tables)}
    scenarios = {r["id"]:r for r in tables["scenarios"]["rows"]}
    events = ["# Generated. Do not edit.\nnamespace = ckcraft\n"]
    loc = {"ckcraft_enable_decision":"CKCraft einschalten", "ckcraft_enable_decision_desc":"Für eine separate Testkampagne: CK3-Reisen mit Minecraft verbinden.","ckcraft_enable_decision_tooltip":"Aktiviert die experimentelle Verbindung.","ckcraft_enable_decision_confirm":"Verbindung aktivieren", "ckcraft_free_travel_decision":"In Minecraft reisen","ckcraft_free_travel_decision_desc":"Deinen tatsächlichen CK3-Charakter in der Minecraft-Testwelt spielen.","ckcraft_free_travel_decision_tooltip":"Die lokale Verbindung erwartet eine Reise.","ckcraft_free_travel_decision_confirm":"Reisen", "ckcraft_cancel_decision":"Ausstehende Minecraft-Reise abbrechen","ckcraft_cancel_decision_desc":"Beendet eine abgebrochene Verbindung ohne Belohnung. Ein verspätetes Ergebnis wird ungültig.","ckcraft_cancel_decision_tooltip":"Nur für die Testkampagne.","ckcraft_cancel_decision_confirm":"Abbrechen"}
    start = """if = { limit = { NOT = { has_variable = ckcraft_sequence } } set_variable = { name = ckcraft_sequence value = 0 } }
        change_variable = { name = ckcraft_sequence add = 1 }
        add_character_flag = ckcraft_pending"""
    for row in tables["scenarios"]["rows"]:
        rid = row["id"]
        if row["enemy"] != "none":
            action = f"""random_courtier_or_guest = {{ limit = {{ is_alive = yes is_adult = yes NOT = {{ this = root }} }} save_scope_as = ckcraft_opponent }}
        if = {{ limit = {{ exists = scope:ckcraft_opponent }}
            {start}
            if = {{ limit = {{ exists = current_travel_plan }} current_travel_plan = {{ pause_travel_plan = yes }} }}
            debug_log = ckcraft_request_{rid}
        }}"""
            opponent = "[SCOPE.sC('ckcraft_opponent').GetID]|[SCOPE.sC('ckcraft_opponent').GetProwess]"
            opponent_name = "[SCOPE.sC('ckcraft_opponent').GetFirstNameNoTooltip]"
        else:
            action = f"{start}\n        debug_log = ckcraft_request_{rid}"
            opponent,opponent_name = "0|0","none"
        events.append(f"""{row['ck3_event']} = {{
    type = character_event
    hidden = yes
    trigger = {{ {GUARD} }}
    immediate = {{
        {action}
    }}
}}
""")
        loc[f"ckcraft_request_{rid}"] = (f"CKCRAFT1|REQUEST|{rid}|[ROOT.Char.GetID]|[ROOT.Char.MakeScope.Var('ckcraft_sequence').GetValue]|[ROOT.Char.GetProwess]|{opponent}|[ROOT.Char.GetCurrentLocation.GetID]|[ROOT.Char.GetFirstNameNoTooltip]|{opponent_name}")
    for row in tables["outcomes"]["rows"]:
        reward = f"add_prestige = {row['prestige']} add_gold = {row['gold']}"
        events.append(f"""{row['ck3_event']} = {{
    type = character_event
    hidden = yes
    trigger = {{ is_ai = no is_alive = yes has_character_flag = ckcraft_pending }}
    immediate = {{
        {reward}
        debug_log = ckcraft_ack_{row['id']}
        remove_character_flag = ckcraft_pending
        if = {{ limit = {{ exists = current_travel_plan }} current_travel_plan = {{ resume_travel_plan = yes }} }}
    }}
}}
""")
        loc[f"ckcraft_ack_{row['id']}"] = f"CKCRAFT1|ACK|[ROOT.Char.GetID]|[ROOT.Char.MakeScope.Var('ckcraft_sequence').GetValue]|{row['id']}"
    result["ck3/ckcraft/events/ckcraft_events.txt"] = "\n".join(events)
    on_actions = ["# Generated. Additive hooks; no vanilla event files are replaced."]
    decisions = ["# Generated.",f"""ckcraft_enable_decision = {{
    is_shown = {{ is_ai = no NOT = {{ has_character_flag = ckcraft_enabled }} }}
    is_valid = {{ is_alive = yes }}
    effect = {{ add_character_flag = ckcraft_enabled }}
    ai_check_interval = 0
}}""", """ckcraft_cancel_decision = {
    is_shown = { is_ai = no has_character_flag = ckcraft_pending }
    is_valid = { is_alive = yes }
    effect = { trigger_event = { id = ckcraft.2003 } }
    ai_check_interval = 0
}"""]
    for hook in tables["hooks"]["rows"]:
        event = scenarios[hook["scenario"]]["ck3_event"]
        if hook["kind"] == "on_action":
            key = f"ckcraft_{hook['id']}"
            on_actions.append(f"{hook['target']} = {{ on_actions = {{ {key} }} }}\n{key} = {{ trigger = {{ {GUARD} }} events = {{ {event} }} }}")
        else:
            decisions.append(f"{hook['target']} = {{\n    is_shown = {{ is_ai = no has_character_flag = ckcraft_enabled }}\n    is_valid = {{ NOT = {{ has_character_flag = ckcraft_pending }} is_alive = yes }}\n    effect = {{ trigger_event = {{ id = {event} }} }}\n    ai_check_interval = 0\n}}")
    result["ck3/ckcraft/common/on_action/ckcraft_on_actions.txt"] = "\n\n".join(on_actions)+"\n"
    result["ck3/ckcraft/common/decisions/ckcraft_decisions.txt"] = "\n\n".join(decisions)+"\n"
    for lang in ["german","english"]:
        result[f"ck3/ckcraft/localization/{lang}/ckcraft_l_{lang}.yml"] = "\ufeffl_"+lang+":\n"+"\n".join(f" {key}:0 {json.dumps(value,ensure_ascii=False)}" for key,value in loc.items())+"\n"
    return result


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("action",choices=["preflight","generate","check"])
    args = parser.parse_args()
    tables = load()
    errors = preflight(tables)
    if errors:
        print("Preflight FAILED:\n"+"\n".join(errors))
        return 1
    cells = sum(len(t["rows"])*len(t["columns"]) for t in tables.values())
    print(f"Preflight: {len(tables)} tables, {cells} filled/type-checked cells, all references resolved.")
    if args.action == "preflight":
        return 0
    files = generate(tables)
    if args.action == "check":
        drift = [p for p,s in files.items() if not (ROOT/p).is_file() or (ROOT/p).read_text(encoding="utf-8") != s]
        if drift:
            print("Generated files missing or stale:\n"+"\n".join(drift))
            return 1
        print("Generated files match the tables.")
    else:
        for p,s in files.items():
            path = ROOT/p
            path.parent.mkdir(parents=True,exist_ok=True)
            path.write_text(s,encoding="utf-8")
        print(f"Generated {len(files)} files.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
